"""seeking_description_nullable_venue

Revision ID: bc09eec43ca5
Revises: c49207d3b4ec
Create Date: 2023-11-18 17:14:49.987236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc09eec43ca5'
down_revision = 'c49207d3b4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
